# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor_7_7 = torch.rand(7, 7)
random_tensor_7_7

tensor([[0.8235, 0.5385, 0.7619, 0.8205, 0.9377, 0.8632, 0.2959],
        [0.1500, 0.9276, 0.4124, 0.1968, 0.5671, 0.1050, 0.3062],
        [0.4178, 0.1853, 0.5400, 0.7108, 0.8149, 0.3389, 0.9359],
        [0.1347, 0.5745, 0.3601, 0.6208, 0.0696, 0.4899, 0.5861],
        [0.2801, 0.5435, 0.6892, 0.7729, 0.2530, 0.4821, 0.0277],
        [0.2820, 0.9246, 0.2923, 0.5496, 0.8917, 0.7857, 0.6373],
        [0.8920, 0.1466, 0.1361, 0.7699, 0.5739, 0.2753, 0.1077]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
random_tensor_1_7 = torch.rand(7,1)
# Perform matrix multiplication
multiplied_tensor = random_tensor_7_7.matmul(random_tensor_1_7)
multiplied_tensor

tensor([[3.0848],
        [1.2461],
        [2.2612],
        [1.5538],
        [1.7717],
        [2.5766],
        [1.9964]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [18]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
rand_one = torch.rand(7,7)
rand_two = torch.rand(7,1)

# Matrix multiply tensors
output_tensor = rand_one.mm(rand_two)
output_tensor, output_tensor.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [36]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"
print(f"The device set is: {device}\n\n")

# Create two random tensors on GPU
rand_one = torch.rand(2,3).to(device)
rand_two = torch.rand(2,3).to(device)

rand_one, rand_two

The device set is: cuda




(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [37]:
# Perform matmul on tensor_A and tensor_B
output_tensor = rand_one.mm(rand_two.T)
output_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [40]:
# Find max
print(f"Max: {output_tensor.max()}")
# Find min
print(f"Min: {output_tensor.min()}")

Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [42]:
# Find arg max
print(f"ArgMax: {output_tensor.argmax()}")

# Find arg min
print(f"ArgMin: {output_tensor.argmin()}")

ArgMax: 3
ArgMin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [48]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor_ex_10 = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed_tensor = random_tensor_ex_10.squeeze()

# Print out tensors and their shapes
random_tensor_ex_10, random_tensor_ex_10.shape, squeezed_tensor, squeezed_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))